"""Machine-readable manifest for the stable public API."""

STABLE_PUBLIC_NAMES = (
    "AdmissionSnapshot",
    "AnyOfTrigger",
    "AsyncPythonTargetRegistry",
    "AsyncioExecutor",
    "AttemptId",
    "BusinessCalendar",
    "BusinessDayTrigger",
    "CalendarProvider",
    "CalendarRef",
    "CalendarRevision",
    "CalendarSnapshotRef",
    "CancellationToken",
    "CleanupResult",
    "Clock",
    "ConcurrencyDecision",
    "ConcurrencyDecisionAction",
    "ConcurrencyMode",
    "ConcurrencyOverflowPolicy",
    "ConcurrencyPolicy",
    "CrashRecoveryActiveRuntimeError",
    "CrashRecoveryError",
    "CrashRecoveryIncompleteError",
    "CrashRecoveryResult",
    "CronAmbiguousTimePolicy",
    "CronDialect",
    "CronNonexistentTimePolicy",
    "CronTrigger",
    "DateTrigger",
    "Duration",
    "ExecutionCancelledError",
    "ExecutionId",
    "ExecutionNotFoundError",
    "ExecutionPolicySnapshot",
    "ExecutionRunSnapshot",
    "ExecutionSnapshot",
    "ExecutionState",
    "Executor",
    "ExecutorOutcome",
    "ExecutorRegistry",
    "ExponentialBackoff",
    "Failure",
    "FailureCategory",
    "FileCalendarProvider",
    "FixedBackoff",
    "GracePeriod",
    "HttpExecutor",
    "HttpMethod",
    "HttpRequestSpec",
    "HttpTargetRegistry",
    "InMemoryCalendarProvider",
    "InMemoryObservationSink",
    "Instant",
    "IntervalTrigger",
    "LocalExecutor",
    "MisfirePolicy",
    "MisfirePolicyAction",
    "NoBackoff",
    "Observation",
    "ObservationSink",
    "OutboxDispatchResult",
    "OutboxMessage",
    "OutboxMessageId",
    "OutboxPublishError",
    "OutboxPublisher",
    "OutboxState",
    "PreparedTarget",
    "PyScheduleKitConfigurationError",
    "PyScheduleKitDeprecationWarning",
    "PyScheduleKitError",
    "PyScheduleKitNotFoundError",
    "PyScheduleKitStateError",
    "PyScheduleKitTargetError",
    "PythonTargetRegistry",
    "ReconciliationActiveRuntimeError",
    "ReconciliationIncompleteError",
    "ReconciliationIssue",
    "ReconciliationResult",
    "RequestId",
    "RetentionPolicy",
    "RetryDecision",
    "RetryDecisionReason",
    "RetryPolicy",
    "RoutingExecutor",
    "RunPendingError",
    "RunPendingResult",
    "RuntimeAlreadyRunningError",
    "ScheduleId",
    "ScheduleNotFoundError",
    "ScheduleSnapshot",
    "ScheduleState",
    "Scheduler",
    "SchedulerHealth",
    "SchedulerReadiness",
    "ShutdownMode",
    "ShutdownResult",
    "SqliteCalendarProvider",
    "SqliteUnitOfWorkFactory",
    "TargetRef",
    "TargetResolutionError",
    "Timezone",
    "Trigger",
    "UnitOfWorkFactory",
    "UnsupportedTargetError",
    "WorkerId",
)

ROOT_METADATA_NAMES = ("__version__",)

POSTGRES_PUBLIC_NAMES = (
    "PostgresUnitOfWorkFactory",
    "TransientPersistenceError",
)

TESTING_PUBLIC_NAMES = (
    "FixedClock",
    "MutableClock",
    "TriggerContractSuite",
    "TriggerContractViolation",
    "add_request_with_parent",
)

PUBLIC_NAMESPACE_CLASSIFICATIONS = {
    "pyschedulekit": "stable-candidate",
    "pyschedulekit.api": "stable-candidate",
    "pyschedulekit.postgres": "stable-candidate",
    "pyschedulekit.testing": "supported-testing",
    "pyschedulekit.experimental": "experimental",
}

LEGACY_ROOT_NAMES = (
    "AdmissionLockOwnershipError",
    "AdmissionToken",
    "ClaimOwnershipError",
    "ClaimToken",
    "ExecutionClaim",
    "ExecutionClaimHandle",
    "ExecutionClaimState",
    "LatenessStatus",
    "ScheduleAdmissionLock",
    "ScheduleAdmissionLockHandle",
    "ScheduleAdmissionLockState",
)

EXPERIMENTAL_PUBLIC_NAMES = LEGACY_ROOT_NAMES
